### ISSUE TITLE
ClassCastException writing String for Bytes

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-extensions#11]
```
11-09 09:23:56.374 27341 27341 W System.err: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
11-09 09:23:56.375 27341 27341 W System.err: 	at edu.mit.appinventor.ble.BluetoothLE.toIntList(BluetoothLE.java:2435)
11-09 09:23:56.375 27341 27341 W System.err: 	at edu.mit.appinventor.ble.BluetoothLE.listFromIterator(BluetoothLE.java:2390)
11-09 09:23:56.375 27341 27341 W System.err: 	at edu.mit.appinventor.ble.BluetoothLE.toList(BluetoothLE.java:2349)
11-09 09:23:56.375 27341 27341 W System.err: 	at edu.mit.appinventor.ble.BluetoothLE.toList(BluetoothLE.java:2347)
11-09 09:23:56.375 27341 27341 W System.err: 	at edu.mit.appinventor.ble.BluetoothLE.ExWriteByteValuesWithResponse(BluetoothLE.java:1788)
11-09 09:23:56.375 27341 27341 W System.err: 	at com.bbc.microbit.profile.Microbit_Uart.WriteRXCharacteristic(Microbit_Uart.java:141)
```

**Comment by ewpatton** [comment]
Fixed via 8f6a850
