### ISSUE TITLE
ClassCastException when using micro:bit with BLE extension

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-extensions#7]
From David Tseng:

Farzeen and I are working on Micro:bit IOpins, but it forced exit the app when Microbit.WritePinData is called -> java.lang.ClassCastException: gnu.mapping.SimpleSymbol cannot be cast to java.lang.Number

![23379785_1420461258002517_1780052025_o](https://user-images.githubusercontent.com/1331253/32514272-821595f6-c3ca-11e7-98c0-21b6d09865f0.png)

When checking the adb log, it seems like something wrong with BluetoothLEint.java (#694, #621). I attach the screenshot and adb log, please take a look of this. 

內置圖片 1

```
​11-06 13:07:20.863  3236  3236 E AndroidRuntime: FATAL EXCEPTION: main
11-06 13:07:20.863  3236  3236 E AndroidRuntime: Process: edu.mit.appinventor.aicompanion3, PID: 3236
11-06 13:07:20.863  3236  3236 E AndroidRuntime: java.lang.ClassCastException: gnu.mapping.SimpleSymbol cannot be cast to java.lang.Number
11-06 13:07:20.863  3236  3236 E AndroidRuntime: 	at edu.mit.appinventor.ble.BluetoothLEint$BLEWriteOperation.write(BluetoothLEint.java:694)
11-06 13:07:20.863  3236  3236 E AndroidRuntime: 	at edu.mit.appinventor.ble.BluetoothLEint$BLEWriteOperation.run(BluetoothLEint.java:621)
11-06 13:07:20.863  3236  3236 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
11-06 13:07:20.863  3236  3236 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-06 13:07:20.863  3236  3236 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:168)
11-06 13:07:20.863  3236  3236 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5885)
11-06 13:07:20.863  3236  3236 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 13:07:20.863  3236  3236 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
11-06 13:07:20.863  3236  3236 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

**Comment by ewpatton** [comment]
Closed via b1dc03b
